name: StochasticModel
channels:
  - https://conda.anaconda.org/gurobi
  - conda-forge
  - bioconda
dependencies:
  # Core
  - python=3.12
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - dask
  - distributed
  - pyomo
  - rust
  - maturin


  # Plotting & Visualization
  - bokeh
  - plotly
  - cartopy

  # Jupyter
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core

  # Async / HTTP / AWS
  - aiohttp
  - aiobotocore
  - botocore
  - aiosignal
  - aioitertools
  - fsspec
  - earthaccess

  # Networking & Compression
  - brotli
  - lz4
  - zlib
  - libzip

  # Data Formats
  - hdf5
  - netcdf4
  - libnetcdf

  # Fonts & Display
  - freetype
  - fonttools
  - cairo
  - harfbuzz

  # Conda utilities
  - conda
  - pip
  - setuptools
  - wheel

  # Solvers (assumes you have a license setup)
  - gurobi
  - cbc

  # Misc
  - cloudpickle
  - dill
  - psutil
  - pqdm
